CREATE TABLE IF NOT EXISTS orders (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    `product_name` VARCHAR(255) NOT NULL ,
    `product_reference` VARCHAR(100) NOT NULL,
    `quantity` INT NOT NULL,
    `price` FLOAT NOT NULL,
    `payment_id` INTEGER
);

CREATE TABLE IF NOT EXISTS payments (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    `currency` VARCHAR(5) NOT NULL ,
    `status` VARCHAR(30) NOT NULL,
    `payment_method` VARCHAR(30) NOT NULL,
    `amount` FLOAT NOT NULL
);
